export const dummyUsers = [
  { _id: "u001", name: "Yagna", email: "yagna@college.com", role: "student", department: "CSE" },
  { _id: "u002", name: "Dr. Ramesh", email: "ramesh@college.com", role: "faculty", department: "CSE" },
  { _id: "u003", name: "Dr. Priya", email: "priya@college.com", role: "hod", department: "CSE" },
  { _id: "u004", name: "Dr. Sharma", email: "sharma@college.com", role: "dean", department: null },
  { _id: "u005", name: "Admin Office", email: "admin@college.com", role: "admin", department: null },
  { _id: "u006", name: "Exam Cell", email: "examcell@college.com", role: "cell", department: null },
  { _id: "u007", name: "CDP Cell", email: "cdp@college.com", role: "cell", department: null },
  { _id: "u008", name: "Library Cell", email: "library@college.com", role: "cell", department: null },
  { _id: "u009", name: "Student Mitra", email: "mitra@college.com", role: "organization", department: null },
  { _id: "u010", name: "SDCAC", email: "sdcac@college.com", role: "organization", department: null },
  { _id: "u011", name: "Helping Hands", email: "hands@college.com", role: "organization", department: null },
  { _id: "u012", name: "Literary Club", email: "literary@college.com", role: "organization", department: null },
]

export const dummyDepartments = [
  { _id: "d001", name: "CSE",      code: "cse" },
  { _id: "d002", name: "AI/ML",    code: "aiml" },
  { _id: "d003", name: "ECE",      code: "ece" },
  { _id: "d004", name: "EEE",      code: "eee" },
  { _id: "d005", name: "MECH",     code: "mech" },
  { _id: "d006", name: "Chemical", code: "chemical" },
  { _id: "d007", name: "Civil",    code: "civil" },
  { _id: "d008", name: "MME",      code: "mme" },
  { _id: "d009", name: "PUC",      code: "puc" },
]

export const dummyAnnouncements = [
  {
    _id: "a001",
    title: "End semester exam schedule released",
    content: "End semester examinations will commence from December 10th. Hall tickets available from Dec 5th. All students must clear dues before collecting hall tickets.",
    category: "exam",
    targetAudience: "all",
    department: null,
    postedBy: { _id: "u006", name: "Exam Cell", role: "cell" },
    isImportant: true,
    createdAt: "2025-03-15",
  },
  {
    _id: "a002",
    title: "Campus recruitment drive — TCS",
    content: "TCS will be conducting a recruitment drive on Dec 18th. Eligible: 2025 passouts with 60% aggregate. Register on the CDP portal before Dec 12th.",
    category: "general",
    targetAudience: "all",
    department: null,
    postedBy: { _id: "u007", name: "CDP Cell", role: "cell" },
    isImportant: true,
    createdAt: "2025-03-14",
  },
  {
    _id: "a003",
    title: "Library book return deadline",
    content: "All borrowed books must be returned by Nov 30th. Fine of Rs.5 per day after the deadline. New books on Data Structures and ML have arrived.",
    category: "general",
    targetAudience: "all",
    department: null,
    postedBy: { _id: "u008", name: "Library Cell", role: "cell" },
    isImportant: false,
    createdAt: "2025-03-13",
  },
  {
    _id: "a004",
    title: "Academic calendar for semester 2 published",
    content: "The academic calendar for Semester 2 has been published. Mid exams: Jan 15-20. End exams: April 10-25. Please plan accordingly.",
    category: "academic",
    targetAudience: "all",
    department: null,
    postedBy: { _id: "u004", name: "Dr. Sharma", role: "dean" },
    isImportant: true,
    createdAt: "2025-03-12",
  },
  {
    _id: "a005",
    title: "CSE internal lab assessment — Unit 3",
    content: "Lab assessment for Unit 3 will be held on Dec 5th for all CSE students. Topics: React, Node.js basics. Bring your lab records.",
    category: "assignment",
    targetAudience: "department",
    department: "CSE",
    postedBy: { _id: "u002", name: "Dr. Ramesh", role: "faculty" },
    isImportant: false,
    createdAt: "2025-03-11",
  },
  {
    _id: "a006",
    title: "CSE department seminar on AI trends",
    content: "A seminar on emerging AI trends will be conducted on Dec 8th in Seminar Hall A. All CSE students and faculty are expected to attend.",
    category: "event",
    targetAudience: "department",
    department: "CSE",
    postedBy: { _id: "u003", name: "Dr. Priya", role: "hod" },
    isImportant: false,
    createdAt: "2025-03-10",
  },
  {
    _id: "a007",
    title: "24hr Hackathon by Student Mitra",
    content: "Student Mitra presents HackFest 2025 — a 24 hour hackathon on Dec 20th. Open to all branches. Team size: 2-4. Prizes worth Rs.50,000. Register now!",
    category: "event",
    targetAudience: "all",
    department: null,
    postedBy: { _id: "u009", name: "Student Mitra", role: "organization" },
    isImportant: false,
    createdAt: "2025-03-09",
  },
  {
    _id: "a008",
    title: "Annual cultural fest — SDCAC",
    content: "SDCAC presents Utsav 2025 on Dec 22nd and 23rd. Events include dance, music, drama, and fine arts. Registrations open for all students.",
    category: "event",
    targetAudience: "all",
    department: null,
    postedBy: { _id: "u010", name: "SDCAC", role: "organization" },
    isImportant: false,
    createdAt: "2025-03-08",
  },
  {
    _id: "a009",
    title: "Blood donation camp — Helping Hands",
    content: "Helping Hands is organizing a blood donation camp on Dec 10th at the college medical center. All healthy students above 18 are encouraged to participate.",
    category: "event",
    targetAudience: "all",
    department: null,
    postedBy: { _id: "u011", name: "Helping Hands", role: "organization" },
    isImportant: false,
    createdAt: "2025-03-07",
  },
  {
    _id: "a010",
    title: "Essay writing competition — Literary Club",
    content: "Literary Club is conducting an essay writing competition on the theme 'Technology and Society' on Dec 15th. Open to all students. Prizes for top 3.",
    category: "event",
    targetAudience: "all",
    department: null,
    postedBy: { _id: "u012", name: "Literary Club", role: "organization" },
    isImportant: false,
    createdAt: "2025-03-06",
  },
]

export const dummyOrganizations = [
  { _id: "o001", name: "Student Mitra", description: "Student welfare body", isApproved: true },
  { _id: "o002", name: "SDCAC", description: "Cultural activities committee", isApproved: true },
  { _id: "o003", name: "Helping Hands", description: "Social service club", isApproved: true },
  { _id: "o004", name: "Literary Club", description: "Writing and debate club", isApproved: true },
  { _id: "o005", name: "Tech Club", description: "Pending approval", isApproved: false },
]